
import Foundation

class Content {
    
    var questionsList = ["When was the last time you felt really happy?",
                         "Are you scared of death?",
                         "What is your fundamental flaw?",
                         "What characteristics do you think people like about you?",
                         "What characteristics do you think people dislike about you?",
                         "What are you materialistic about?",
                         "What makes you different?",
                         "Where do you feel most comfortable?",
                         "When was the last time you cried?",
                         "What do you wish you could tell your five year old self?",
                         "What is something you are afraid to admit?",
                         "What do you love about being human?",
                         "What are you insecure about?",
                         "What do you love about yourself?",
                         "What do you look for in a romantic partner?",
                         "What is something you think no one would accept about you?",
                         "Truthfully, how are you feeling right now?",
                         "If you could eat only one food for the rest of your life, what would it be?",
                         "Who is someone you would like to get closer to?",
                         "What do you look forward to every day?",
                         "How do you feel about your relationship status?",
                         "What is your favorite weather?",
                         "What was the last movie you've watched?",
                         "Do you get enough sleep?",
                         "What is one food you find disgusting?",
                         "What annoys you?",
                         "Do you consider yourself open-minded?",
                         "What age would you like to be?",
                         "How long would you want to live?",
                         "What is your go-to icebreaker?",
                         "What is something you find rude that others don't?",
                         "What is your favorite compliment?",
                         "What is your unusual fear?",
                         "What do you think you do better than most people?",
                         "What's the most physically painful thing you've experienced?",
                         "Do you care about your birthday?",
                         "Does beauty matter to you?",
                         "What's the cruelest thing you have ever done?",
                         "What's the cruelest thing someone has done to you?",
                         "What are you most proud of?",
                         "What do you wish was a social norm?",
                         "What makes you hate others?",
                         "Is romance a big deal to you?",
                         "What do you wish you were good at?",
                         "What's a song that gets to you?",
                         "What is your favorite pleasure?"]
    
    var answersList = ["Write about someone you admire. What do you admire about this person?",
                       "Write a letter to your past self two years back in time.",
                       "Write about the things that make you feel alive.",
                       "Write about a time you felt deeply embarrassed.",
                       "Write a letter to someone who is no longer a part of your life.",
                       "Describe how certain you are with your sexuality, and how you came to that answer.",
                       "Think about a time where you felt extremely low. Write about how you endured that time.",
                       "Write about someone you're not close with, but you appreciate their existence.",
                       "Write about an important lesson you've learned from a past misfortune.",
                       "Write about someone you miss.",
                       "Write about a place you've always wanted to travel.",
                       "Write a letter which you can read to yourself when you're feeling lonely.",
                       "Write about something you regret doing.",
                       "Write about something you regret not doing.",
                       "Write about a dream that really moved you emotionally.",
                       "Write about something you used to dislike about yourself, that you are now content with.",
                       "Explain a dark truth that you find difficult to accept.",
                       "Write about some challenges that have shaped who you are.",
                       "Think about a memory that makes you smile!",
                       "Make a list of the top 5 things you value in life.",
                       "Write about someone who makes you feel safe.",
                       "Write about a moment you would like to experience again."]
    
    var phraseList = ["I have at least one person I can be vulnerable with.",
                      "I feel that no one will truly understand me.",
                      "I think I am really messed up.",
                      "I am happy with what I currently have.",
                      "Sometimes, I think about what would happen if I suddenly disappeared.",
                      "I have been emotionally damaged in the past.",
                      "I am really good at pretending that I am normal.",
                      "I think I am emotionally fragile.",
                      "I feel sad most of the time.",
                      "The thought of being alone is both comforting and terrifying.",
                      "I can take care of myself.",
                      "I often compare myself to others. It doesn't end up well.",
                      "I feel the need to always be doing something productive.",
                      "I am scared of growing older.",
                      "I am scared of missing out.",
                      "I enjoy seeing my loved ones happy.",
                      "I don't really know what I want to do with my life.",
                      "I have a healthy amount of self-esteem.",
                      "I doubt myself too often.",
                      "I think about the past a lot. Probably way too much.",
                      "I tend to overthink things and it does not go well for me.",
                      "I think that true love exists.",
                      "I believe in the idea of a soul mate.",
                      "I see the good in people more than I see the bad.",
                      "I acknowledge that people change.",
                      "I have problems when it comes to trusting other people.",
                      "Deep down, I am not content with my relationship status.",
                      "Sometimes, I feel that I'm boring.",
                      "I'm really shy. I'm just good at hiding it.",
                      "I think I'm awkward.",
                      "Sometimes, I just really need a hug.",
                      "I am more pessimistic than I am optimistic.",
                      "I might be too hard on myself sometimes.",
                      "I get angry way too easily.",
                      "I am highly sensitive."]
    
}
